/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package com.github.lburgazzoli.camel.salesforce.model;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist BillingGeocodeAccuracy
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Order_BillingGeocodeAccuracyEnum {

    // Address
    ADDRESS("Address"),
    // Block
    BLOCK("Block"),
    // City
    CITY("City"),
    // County
    COUNTY("County"),
    // ExtendedZip
    EXTENDEDZIP("ExtendedZip"),
    // NearAddress
    NEARADDRESS("NearAddress"),
    // Neighborhood
    NEIGHBORHOOD("Neighborhood"),
    // State
    STATE("State"),
    // Street
    STREET("Street"),
    // Unknown
    UNKNOWN("Unknown"),
    // Zip
    ZIP("Zip");

    final String value;

    private Order_BillingGeocodeAccuracyEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Order_BillingGeocodeAccuracyEnum fromValue(String value) {
        for (Order_BillingGeocodeAccuracyEnum e : Order_BillingGeocodeAccuracyEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
